class Daisy{
  constructor(){
    this.x=315
    this.y=315
    this.size=90
    this.xSpeed=0
    this.ySpeed=0
    this.direction=3
  }
  move(){
    this.x+=this.xSpeed
    this.y+=this.ySpeed
    this.x=constrain(this.x,15,620)
    this.y=constrain(this.y,0,615)
  }
  show(){
    if(this.direction==1){
      image(DaisyUp,this.x,this.y,this.size,this.size)
    }
    if(this.direction==2){
      image(DaisyRight,this.x,this.y,this.size,this.size)
    }
    if(this.direction==3){
      image(DaisyDown,this.x,this.y,this.size,this.size)
    }
    if(this.direction==4){
      image(DaisyLeft,this.x,this.y,this.size,this.size)
    }
  }
  up(){
    this.direction=1
    this.ySpeed=difficulty*-4
  }
  right(){
    this.direction=2
    this.xSpeed=difficulty*4
  }
  down(){
    this.direction=3
    this.ySpeed=difficulty*4
  }
  left(){
    this.direction=4
    this.xSpeed=difficulty*-4
  }
}