class Player1{
  constructor(){
    this.x=220
    this.y=330
    this.size=60
    this.xSpeed=0
    this.ySpeed=0
    this.direction=3
  }
  move(){
    this.x+=this.xSpeed
    this.y+=this.ySpeed
    this.x=constrain(this.x,10,440)
    this.y=constrain(this.y,110,540)
  }
  show(){
    if(this.direction==1){
      image(RoddyUp,this.x,this.y,this.size,this.size)
    }
    if(this.direction==2){
      image(RoddyRight,this.x,this.y,this.size,this.size)
    }
    if(this.direction==3){
      image(RoddyDown,this.x,this.y,this.size,this.size)
    }
    if(this.direction==4){
      image(RoddyLeft,this.x,this.y,this.size,this.size)
    }
  }
  up(){
    this.direction=1
    this.ySpeed=difficulty*-2.7
  }
  right(){
    this.direction=2
    this.xSpeed=difficulty*2.7
  }
  down(){
    this.direction=3
    this.ySpeed=difficulty*2.7
  }
  left(){
    this.direction=4
    this.xSpeed=difficulty*-2.7
  }
}