class Rat2{
  constructor(){
    this.x=315
    this.y=315
    this.size=90
    this.xSpeed=0
    this.ySpeed=0
    this.direction=3
  }
  move(){
    this.x+=this.xSpeed
    this.y+=this.ySpeed
    this.x=constrain(this.x,15,620)
    this.y=constrain(this.y,0,615)
  }
  show(){
    image(alphaRat2,this.x,this.y,this.size,this.size)
  }
  up(){
    this.direction=1
    this.ySpeed=difficulty*-5
  }
  right(){
    this.direction=2
    this.xSpeed=difficulty*5
  }
  down(){
    this.direction=3
    this.ySpeed=difficulty*5
  }
  left(){
    this.direction=4
    this.xSpeed=difficulty*-5
  }
}